# Site wide configuration

title: "Mandy Chen's Blog"
description: "A site to record everything I learned from Feb.19th, 2017."
logo: Avatar.jpg # 120x120 px default image used for Twitter summary card
teaser: default_teaser.jpg # 400x250 px default teaser image used in image archive grid
locale: en
url: 
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner: 
  name: "Mandy Chen"
  email: "jiayaochen93@gmail.com"
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: Avatar.jpg # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
  - _pages
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp

author:
  name   : "Mandy Chen"
  avatar : "/images/Avatar.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  email  : # optional
  uri    : "https://mandychen0114.github.io"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true